### ISSUE TITLE
Create symlinks for latest environments on mozqa.com

### ISSUE THREAD

**Issue by cosmin-malutan** [mozilla/mozmill-environment#72]
As discussed in mozmill-crowd repository https://github.com/whimboo/mozmill-crowd/pull/14#discussion_r10468446 we would need either to add a symlink to the latest -environment or to add the latest environment twice, once to overwrite a latest.zip file.

**Comment by whimboo** [comment]
I have a script which I run manually for now on the host, which looks like:

> #/!/bin/bash
cd /data/www/mozqa.com/mozmill-env/
rm latest-*
ln -s ${1}-linux.zip latest-linux.zip
ln -s ${1}-windows.zip latest-windows.zip
ln -s ${1}-mac.zip latest-mac.zip
echo ${1} > latest.txt
chmod 666 latest.txt
ls -l latest*

I think that could help someone to get the `upload.sh` script updated.
